version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Server=db;Database=base_core;User=sonmc;Password=123456
    networks:
      - mynetwork  # Linking the web service to the custom network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=base_core
      - POSTGRES_USER=sonmc
      - POSTGRES_PASSWORD=123456
    networks:
      - mynetwork  # Linking the db service to the custom network

networks:
  mynetwork:  # Defining a custom network
    driver: bridge

volumes:
  pgdata:
