version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Server=db;Database=base_core;User=sonmc;Password=123456
    networks:
      - mynetwork 
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=base_core

volumes:
  mysql_data: