version: '3.0'

services:
   db:
     image: mysql:8.0
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: base_core
       MYSQL_USER: sonmc
       MYSQL_PASSWORD: 123456
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

   base_core:
     depends_on:
       - db
     image: codemazeblog/base_core:runtime
     build:
       context: .
     ports:
       - "3307:3306"

volumes:
    dbdata: