version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Server=db;Database=base_core;User=root;Password=123456;Port=3307

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=base_core
volumes:
      mysql_data: 

      root:
        depends_on:
          - db